from __future__ import annotations

from app.integrations.capabilities import ToolCapability
from app.integrations.providers import (
    PROVIDER_DISCORD_WEBHOOK,
    PROVIDER_FACEBOOK_GRAPH_OAUTH,
    PROVIDER_FEISHU_WEBHOOK,
    PROVIDER_GOOGLE_YOUTUBE_OAUTH,
    PROVIDER_LINKEDIN_OAUTH,
    PROVIDER_REDDIT_OAUTH,
    PROVIDER_SLACK_INCOMING_WEBHOOK,
    PROVIDER_SLACK_OAUTH,
    PROVIDER_TELEGRAM_BOT,
    PROVIDER_TWITTER_OAUTH,
    PROVIDER_WECHAT_MP_CREDENTIALS,
    PROVIDER_WECHAT_WORK_WEBHOOK,
    PROVIDER_WEIBO_OAUTH,
    PROVIDER_WHATSAPP_CLOUD,
)

CAPABILITIES: tuple[ToolCapability, ...] = (
    ToolCapability(
        id="apollo_search",
        category="crm",
        display_name="Apollo.io 联系人搜索",
        description="按域名/职位等搜索潜在客户（需服务端 APOLLO_API_KEY）。",
        auth_mode="api_key",
        status="live",
        env_keys=("apollo_api_key",),
        roles_hint=("hunter", "sdr", "bd"),
        bill_unit_usd=0.01,
    ),
    ToolCapability(
        id="resend_email",
        category="email",
        display_name="Resend 发信",
        description="通过 Resend 发送事务邮件（需服务端 RESEND_API_KEY）。",
        auth_mode="api_key",
        status="live",
        env_keys=("resend_api_key",),
        roles_hint=("outreach", "customer_success", "marketing"),
        bill_unit_usd=0.005,
    ),
    ToolCapability(
        id="slack_post_message",
        category="messaging",
        display_name="Slack 发消息",
        description="使用 Slack OAuth 机器人发频道消息，或配置 Incoming Webhook 发文本。",
        auth_mode="oauth2",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_SLACK_OAUTH, PROVIDER_SLACK_INCOMING_WEBHOOK),
        oauth_server_env_keys=("slack_client_id", "slack_client_secret", "titan_api_public_base_url"),
        roles_hint=("manager", "operations", "support"),
    ),
    ToolCapability(
        id="discord_post_message",
        category="messaging",
        display_name="Discord Webhook",
        description="向频道发送消息：在控制台保存 Discord Webhook URL（加密存储）后即可调用。",
        auth_mode="user_token",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_DISCORD_WEBHOOK,),
        roles_hint=("community", "support", "marketing"),
    ),
    ToolCapability(
        id="twitter_x_post",
        category="social",
        display_name="X (Twitter) 发帖",
        description="OAuth 2.0 用户授权后代发推文（需配置 Twitter Developer Portal 回调 URL）。",
        auth_mode="oauth2",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_TWITTER_OAUTH,),
        oauth_server_env_keys=("twitter_client_id", "twitter_client_secret", "titan_api_public_base_url"),
        roles_hint=("marketing", "pr", "founder"),
    ),
    ToolCapability(
        id="linkedin_share",
        category="social",
        display_name="LinkedIn 动态",
        description="OAuth 2.0 授权后在个人主页发布公开动态。",
        auth_mode="oauth2",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_LINKEDIN_OAUTH,),
        oauth_server_env_keys=("linkedin_client_id", "linkedin_client_secret", "titan_api_public_base_url"),
        roles_hint=("marketing", "hr", "bd"),
    ),
    ToolCapability(
        id="wechat_work_notify",
        category="messaging",
        display_name="企业微信机器人",
        description="群机器人 Webhook：保存机器人 URL 后可发 Markdown 通知。",
        auth_mode="api_key",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_WECHAT_WORK_WEBHOOK,),
        roles_hint=("operations", "manager", "support"),
    ),
    ToolCapability(
        id="feishu_lark_notify",
        category="messaging",
        display_name="飞书 / Lark 机器人",
        description="自定义机器人 Webhook 发送文本消息。",
        auth_mode="api_key",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_FEISHU_WEBHOOK,),
        roles_hint=("operations", "manager", "engineering"),
    ),
    ToolCapability(
        id="telegram_send_message",
        category="messaging",
        display_name="Telegram Bot 发消息",
        description="使用 BotFather 的 bot token 向指定 chat_id 发送文本（凭证加密存储）。",
        auth_mode="user_token",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_TELEGRAM_BOT,),
        roles_hint=("operations", "community", "support"),
        version="v1",
        quota_per_minute=60,
        bill_unit_usd=0.002,
    ),
    ToolCapability(
        id="whatsapp_cloud_text",
        category="messaging",
        display_name="WhatsApp Cloud API 文本",
        description="Meta WhatsApp Cloud：保存系统用户 access_token + phone_number_id 后向 E.164 号码发文本。",
        auth_mode="user_token",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_WHATSAPP_CLOUD,),
        roles_hint=("operations", "support", "sales"),
    ),
    ToolCapability(
        id="facebook_page_feed_post",
        category="social",
        display_name="Facebook 公共主页发帖",
        description="OAuth 后使用 Page access token 在主页时间线发帖（可选 link）。",
        auth_mode="oauth2",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_FACEBOOK_GRAPH_OAUTH,),
        oauth_server_env_keys=("facebook_app_id", "facebook_app_secret", "titan_api_public_base_url"),
        roles_hint=("marketing", "pr", "community"),
    ),
    ToolCapability(
        id="instagram_publish_image",
        category="social",
        display_name="Instagram 商业账号发图",
        description="与 Facebook 同一 OAuth；需主页绑定 IG 商业账号。发布单张图片（image_url + caption）。",
        auth_mode="oauth2",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_FACEBOOK_GRAPH_OAUTH,),
        oauth_server_env_keys=("facebook_app_id", "facebook_app_secret", "titan_api_public_base_url"),
        roles_hint=("marketing", "design", "community"),
    ),
    ToolCapability(
        id="weibo_status_post",
        category="social",
        display_name="新浪微博发博",
        description="微博开放平台 OAuth2 后调用 statuses/update 发文字微博。",
        auth_mode="oauth2",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_WEIBO_OAUTH,),
        oauth_server_env_keys=("weibo_app_key", "weibo_app_secret", "titan_api_public_base_url"),
        roles_hint=("marketing", "pr", "founder"),
    ),
    ToolCapability(
        id="reddit_submit_post",
        category="social",
        display_name="Reddit 发帖",
        description="OAuth 后在指定 subreddit 提交 self 或 link 帖子（需 Reddit App 回调配置）。",
        auth_mode="oauth2",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_REDDIT_OAUTH,),
        oauth_server_env_keys=("reddit_client_id", "reddit_client_secret", "titan_api_public_base_url"),
        roles_hint=("community", "marketing", "product"),
    ),
    ToolCapability(
        id="youtube_top_comment",
        category="social",
        display_name="YouTube 视频评论",
        description="Google OAuth（youtube.force-ssl）后在指定视频下发表顶级评论。",
        auth_mode="oauth2",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_GOOGLE_YOUTUBE_OAUTH,),
        oauth_server_env_keys=("google_oauth_client_id", "google_oauth_client_secret", "titan_api_public_base_url"),
        roles_hint=("community", "marketing", "creator"),
    ),
    ToolCapability(
        id="wechat_mp_template_message",
        category="messaging",
        display_name="微信公众号模板消息",
        description="服务号 appid + secret（加密存储），向已关注用户发送模板消息（需模板与行业类目）。",
        auth_mode="api_key",
        status="live",
        env_keys=(),
        connection_provider_any=(PROVIDER_WECHAT_MP_CREDENTIALS,),
        roles_hint=("operations", "customer_success", "marketing"),
    ),
    ToolCapability(
        id="douyin_content_stub",
        category="social",
        display_name="抖音（占位）",
        description="字节系无稳定公开「代发」HTTP API；需官方合作或开放平台单独签约后接入。",
        auth_mode="user_token",
        status="stub",
        env_keys=(),
        roles_hint=("marketing", "creator"),
    ),
    ToolCapability(
        id="xiaohongshu_content_stub",
        category="social",
        display_name="小红书（占位）",
        description="商业笔记/发布接口多为合作渠道或企业号专用，无通用自助 API。",
        auth_mode="user_token",
        status="stub",
        env_keys=(),
        roles_hint=("marketing", "ecommerce"),
    ),
    ToolCapability(
        id="bilibili_publish_stub",
        category="social",
        display_name="哔哩哔哩投稿（占位）",
        description="开放能力以 OAuth 投稿为主且需应用审核；此处仅占位，后续可接官方 SDK。",
        auth_mode="oauth2",
        status="stub",
        env_keys=(),
        roles_hint=("creator", "marketing"),
    ),
    ToolCapability(
        id="zhihu_content_stub",
        category="social",
        display_name="知乎内容（占位）",
        description="无面向第三方的通用「发帖」开放接口；占位用于产品与合规规划。",
        auth_mode="user_token",
        status="stub",
        env_keys=(),
        roles_hint=("marketing", "pr"),
    ),
    ToolCapability(
        id="weixin_channels_stub",
        category="social",
        display_name="微信视频号（占位）",
        description="视频号分发以微信生态内能力为主，通用服务器代发需按腾讯最新政策接入。",
        auth_mode="user_token",
        status="stub",
        env_keys=(),
        roles_hint=("marketing", "creator"),
    ),
    ToolCapability(
        id="tiktok_publish_stub",
        category="social",
        display_name="TikTok 发布（占位）",
        description="TikTok Content Posting API 需单独申请与 scopes；未配置前为占位。",
        auth_mode="oauth2",
        status="stub",
        env_keys=(),
        roles_hint=("marketing", "creator"),
    ),
    ToolCapability(
        id="threads_publish_stub",
        category="social",
        display_name="Threads（占位）",
        description="Threads/Instagram 新接口以 Meta 文档为准；与 IG Graph 能力可能合并演进。",
        auth_mode="oauth2",
        status="stub",
        env_keys=(),
        roles_hint=("marketing", "community"),
    ),
    ToolCapability(
        id="pinterest_pin_stub",
        category="social",
        display_name="Pinterest Pin（占位）",
        description="Pinterest Marketing API 需 OAuth 与广告主权限；后续可接 v5 Pin create。",
        auth_mode="oauth2",
        status="stub",
        env_keys=(),
        roles_hint=("marketing", "design"),
    ),
    ToolCapability(
        id="snapchat_content_stub",
        category="social",
        display_name="Snapchat 内容（占位）",
        description="Snap Marketing / Creative API 以广告与素材为主，通用发帖需按官方产品接入。",
        auth_mode="user_token",
        status="stub",
        env_keys=(),
        roles_hint=("marketing", "brand"),
    ),
    ToolCapability(
        id="openai_image_generate",
        category="media",
        display_name="图像生成 (OpenAI 兼容)",
        description="文生图（需 OPENAI_API_KEY 或其它已配置模型 Key，占位路由）。",
        auth_mode="api_key",
        status="stub",
        env_keys=("openai_api_key",),
        roles_hint=("design", "marketing", "product"),
    ),
    ToolCapability(
        id="github_create_pr",
        category="code",
        display_name="GitHub 创建 PR",
        description="从分支创建 Pull Request（需 PAT / GitHub App，占位）。",
        auth_mode="user_token",
        status="stub",
        env_keys=(),
        roles_hint=("engineering", "devops", "tech_lead"),
    ),
    ToolCapability(
        id="gitlab_create_mr",
        category="code",
        display_name="GitLab 创建 MR",
        description="创建 Merge Request（占位）。",
        auth_mode="user_token",
        status="stub",
        env_keys=(),
        roles_hint=("engineering", "devops"),
    ),
    ToolCapability(
        id="context_sync_run",
        category="context",
        display_name="上下文同步（Gmail / Calendar / GitHub）",
        description="手动触发租户 Context Sync 管道（Gmail / Calendar / GitHub）。",
        auth_mode="none",
        status="live",
        env_keys=(),
        roles_hint=("manager", "operations", "researcher"),
        bill_unit_usd=0.002,
    ),
    ToolCapability(
        id="computer_use_submit",
        category="desktop",
        display_name="计算机使用 — 提交任务",
        description="在云沙箱中执行 GUI 自动化指令（M03 上线后 live）。",
        auth_mode="none",
        status="stub",
        env_keys=(),
        roles_hint=("delivery", "operations", "researcher"),
        bill_unit_usd=0.05,
    ),
    ToolCapability(
        id="computer_use_status",
        category="desktop",
        display_name="计算机使用 — 查询状态",
        description="查询 computer_use_submit 的运行状态。",
        auth_mode="none",
        status="stub",
        env_keys=(),
        roles_hint=("delivery", "operations", "researcher"),
    ),
    ToolCapability(
        id="computer_use_cancel",
        category="desktop",
        display_name="计算机使用 — 取消任务",
        description="取消进行中的 GUI 自动化运行。",
        auth_mode="none",
        status="stub",
        env_keys=(),
        roles_hint=("delivery", "operations", "manager"),
    ),
)

def _build_capability_index() -> dict[str, ToolCapability]:
    idx: dict[str, ToolCapability] = {}
    for cap in CAPABILITIES:
        idx[cap.id] = cap
        if cap.version:
            idx[f"{cap.id}@{cap.version}"] = cap
    return idx


CAPABILITY_INDEX: dict[str, ToolCapability] = _build_capability_index()


def get_capability(capability_id: str) -> ToolCapability | None:
    from app.integrations.capability_version import resolve_capability_ref

    resolved = resolve_capability_ref(capability_id, index=CAPABILITY_INDEX)
    return resolved.capability if resolved else None


def resolve_capability(capability_id: str):
    from app.integrations.capability_version import resolve_capability_ref

    return resolve_capability_ref(capability_id, index=CAPABILITY_INDEX)


def all_capability_ids() -> frozenset[str]:
    ids: set[str] = set()
    for cap in CAPABILITIES:
        ids.add(cap.id)
        if cap.version:
            ids.add(f"{cap.id}@{cap.version}")
    return frozenset(ids)
