"""Global industry sectors (ISIC Rev.4 inspired, business-oriented granularity).

Used to auto-register catalog industry plugins. IDs are stable API keys (snake_case).
"""

from __future__ import annotations

from typing import TypedDict


class IndustryRow(TypedDict):
    id: str
    name_en: str
    name_zh: str
    icon: str


# ~88 sectors: broad geography-neutral coverage; extend by appending rows.
INDUSTRY_CATALOG: list[IndustryRow] = [
    {"id": "sec_crop_animal", "name_en": "Crop & animal production", "name_zh": "作物与畜牧生产", "icon": "🌾"},
    {"id": "sec_forestry_logging", "name_en": "Forestry & logging", "name_zh": "林业与采伐", "icon": "🌲"},
    {"id": "sec_fishing_aquaculture", "name_en": "Fishing & aquaculture", "name_zh": "渔业与水产养殖", "icon": "🎣"},
    {"id": "sec_mining_coal", "name_en": "Mining of coal", "name_zh": "煤炭开采", "icon": "⛏️"},
    {"id": "sec_mining_metal", "name_en": "Mining of metal ores", "name_zh": "金属矿石开采", "icon": "⛏️"},
    {"id": "sec_mining_nonmetal", "name_en": "Other mining & quarrying", "name_zh": "其他采矿采石", "icon": "🪨"},
    {"id": "sec_food_beverage_mfg", "name_en": "Food & beverage manufacturing", "name_zh": "食品饮料制造", "icon": "🍞"},
    {"id": "sec_textiles_apparel", "name_en": "Textiles & apparel manufacturing", "name_zh": "纺织服装制造", "icon": "🧵"},
    {"id": "sec_wood_paper_mfg", "name_en": "Wood, paper & printing", "name_zh": "木材、造纸与印刷", "icon": "📄"},
    {"id": "sec_petroleum_chemical", "name_en": "Petroleum, chemical & pharma mfg", "name_zh": "石化、化工与医药制造", "icon": "🧪"},
    {"id": "sec_rubber_plastic_mfg", "name_en": "Rubber & plastics products", "name_zh": "橡胶塑料制品", "icon": "♻️"},
    {"id": "sec_nonmetallic_mfg", "name_en": "Non-metallic mineral products", "name_zh": "非金属矿物制品", "icon": "🧱"},
    {"id": "sec_basic_metals_mfg", "name_en": "Basic metals manufacturing", "name_zh": "基本金属冶炼与加工", "icon": "🔩"},
    {"id": "sec_fabricated_metal_mfg", "name_en": "Fabricated metal products", "name_zh": "金属制品", "icon": "⚙️"},
    {"id": "sec_computer_electronics_mfg", "name_en": "Computer & electronics manufacturing", "name_zh": "计算机与电子设备制造", "icon": "💻"},
    {"id": "sec_electrical_equipment_mfg", "name_en": "Electrical equipment manufacturing", "name_zh": "电气设备制造", "icon": "🔌"},
    {"id": "sec_machinery_mfg", "name_en": "Machinery & equipment manufacturing", "name_zh": "机械设备制造", "icon": "🏭"},
    {"id": "sec_auto_transport_mfg", "name_en": "Motor vehicles & transport equipment mfg", "name_zh": "汽车与运输设备制造", "icon": "🚗"},
    {"id": "sec_furniture_mfg", "name_en": "Furniture & other manufacturing", "name_zh": "家具及其他制造", "icon": "🛋️"},
    {"id": "sec_utility_power", "name_en": "Electricity, gas, steam & air conditioning", "name_zh": "电力、燃气、蒸汽与空调供应", "icon": "⚡"},
    {"id": "sec_water_waste", "name_en": "Water, sewerage & waste management", "name_zh": "供水、排污与废弃物管理", "icon": "💧"},
    {"id": "sec_construction", "name_en": "Construction", "name_zh": "建筑业", "icon": "🏗️"},
    {"id": "sec_wholesale_trade", "name_en": "Wholesale trade", "name_zh": "批发贸易", "icon": "📦"},
    {"id": "sec_retail_trade", "name_en": "Retail trade (incl. e-commerce)", "name_zh": "零售贸易（含电商）", "icon": "🛒"},
    {"id": "sec_motor_vehicle_retail", "name_en": "Motor vehicle retail & repair", "name_zh": "机动车零售与维修", "icon": "🔧"},
    {"id": "sec_transport_land", "name_en": "Land transport & logistics", "name_zh": "陆运与物流", "icon": "🚚"},
    {"id": "sec_transport_water", "name_en": "Water transport", "name_zh": "水运", "icon": "🚢"},
    {"id": "sec_transport_air", "name_en": "Air transport", "name_zh": "空运", "icon": "✈️"},
    {"id": "sec_warehousing_support", "name_en": "Warehousing & transport support", "name_zh": "仓储与运输辅助", "icon": "📫"},
    {"id": "sec_post_telecom", "name_en": "Postal & courier activities", "name_zh": "邮政与快递", "icon": "📮"},
    {"id": "sec_accommodation", "name_en": "Accommodation (hotels & lodging)", "name_zh": "住宿服务", "icon": "🏨"},
    {"id": "sec_food_service", "name_en": "Food & beverage service", "name_zh": "餐饮服务", "icon": "🍽️"},
    {"id": "sec_publishing", "name_en": "Publishing", "name_zh": "出版", "icon": "📚"},
    {"id": "sec_broadcast_media", "name_en": "Broadcasting & audiovisual media", "name_zh": "广播与视听媒体", "icon": "📺"},
    {"id": "sec_telecommunications", "name_en": "Telecommunications", "name_zh": "电信", "icon": "📡"},
    {"id": "sec_software_it_services", "name_en": "Software & IT services", "name_zh": "软件与信息技术服务", "icon": "💾"},
    {"id": "sec_cloud_data_infra", "name_en": "Cloud, data centres & digital infra", "name_zh": "云、数据中心与数字基础设施", "icon": "☁️"},
    {"id": "sec_cybersecurity", "name_en": "Cybersecurity services", "name_zh": "网络安全服务", "icon": "🔐"},
    {"id": "sec_ai_data_analytics", "name_en": "AI, data science & analytics services", "name_zh": "人工智能、数据科学与分析服务", "icon": "🤖"},
    {"id": "sec_financial_services", "name_en": "Financial services (excl. insurance)", "name_zh": "金融服务（不含保险）", "icon": "🏦"},
    {"id": "sec_insurance_reinsurance", "name_en": "Insurance & reinsurance", "name_zh": "保险与再保险", "icon": "🛡️"},
    {"id": "sec_payments_fintech", "name_en": "Payments & fintech platforms", "name_zh": "支付与金融科技平台", "icon": "💳"},
    {"id": "sec_investment_asset_mgmt", "name_en": "Investment & asset management", "name_zh": "投资与资产管理", "icon": "📈"},
    {"id": "sec_real_estate", "name_en": "Real estate activities", "name_zh": "房地产", "icon": "🏢"},
    {"id": "sec_legal_accounting", "name_en": "Legal, accounting & advisory", "name_zh": "法律、会计与咨询", "icon": "⚖️"},
    {"id": "sec_management_consulting", "name_en": "Management consulting", "name_zh": "管理咨询", "icon": "📊"},
    {"id": "sec_architecture_engineering", "name_en": "Architecture & engineering services", "name_zh": "建筑与工程技术服务", "icon": "📐"},
    {"id": "sec_scientific_rd", "name_en": "Scientific R&D services", "name_zh": "科研与研发服务", "icon": "🔬"},
    {"id": "sec_advertising_market_research", "name_en": "Advertising & market research", "name_zh": "广告与市场研究", "icon": "📣"},
    {"id": "sec_professional_other", "name_en": "Other professional & technical services", "name_zh": "其他专业技术服务", "icon": "🧰"},
    {"id": "sec_facilities_admin", "name_en": "Facilities, admin & business support", "name_zh": "设施、行政与商务支持", "icon": "🗂️"},
    {"id": "sec_employment_agencies", "name_en": "Employment & HR services", "name_zh": "就业与人力资源服务", "icon": "🤝"},
    {"id": "sec_travel_support", "name_en": "Travel, reservation & support services", "name_zh": "旅行预订与支持服务", "icon": "🧳"},
    {"id": "sec_security_investigation", "name_en": "Security & investigation services", "name_zh": "安保与调查服务", "icon": "🛂"},
    {"id": "sec_public_admin", "name_en": "Public administration & defence", "name_zh": "公共管理与国防", "icon": "🏛️"},
    {"id": "sec_education", "name_en": "Education", "name_zh": "教育", "icon": "🎓"},
    {"id": "sec_health_human_services", "name_en": "Human health & social work", "name_zh": "医疗卫生与社会工作", "icon": "🏥"},
    {"id": "sec_arts_entertainment", "name_en": "Arts, entertainment & recreation", "name_zh": "艺术、娱乐与休闲", "icon": "🎭"},
    {"id": "sec_libraries_museums", "name_en": "Libraries, museums & heritage", "name_zh": "图书馆、博物馆与文化遗产", "icon": "🏛️"},
    {"id": "sec_sports_gambling", "name_en": "Sports, gambling & recreation services", "name_zh": "体育、博彩与休闲服务", "icon": "🎰"},
    {"id": "sec_other_personal_services", "name_en": "Other personal services", "name_zh": "其他个人服务", "icon": "💇"},
    {"id": "sec_nonprofit_ngo", "name_en": "Non-profit & NGOs", "name_zh": "非营利组织与 NGO", "icon": "🕊️"},
    {"id": "sec_membership_orgs", "name_en": "Membership organisations", "name_zh": "会员制组织", "icon": "🤝"},
    {"id": "sec_extraterritorial", "name_en": "Extraterritorial organisations", "name_zh": "境外组织与代表处", "icon": "🌐"},
    {"id": "sec_agriculture_tech", "name_en": "Agri-tech & precision agriculture", "name_zh": "农业科技与精准农业", "icon": "🛰️"},
    {"id": "sec_energy_renewables", "name_en": "Renewable energy & storage", "name_zh": "可再生能源与储能", "icon": "🔋"},
    {"id": "sec_oil_gas", "name_en": "Oil & gas upstream/midstream", "name_zh": "油气上游与中游", "icon": "🛢️"},
    {"id": "sec_mining_tech", "name_en": "Mining technology & services", "name_zh": "采矿技术与服务", "icon": "⛏️"},
    {"id": "sec_semiconductor", "name_en": "Semiconductor design & manufacturing", "name_zh": "半导体设计与制造", "icon": "🧩"},
    {"id": "sec_aerospace_defense", "name_en": "Aerospace & defence", "name_zh": "航空航天与国防", "icon": "🚀"},
    {"id": "sec_automotive_mobility", "name_en": "Automotive & mobility platforms", "name_zh": "汽车与出行平台", "icon": "🛞"},
    {"id": "sec_consumer_electronics", "name_en": "Consumer electronics", "name_zh": "消费电子", "icon": "📱"},
    {"id": "sec_industrial_automation", "name_en": "Industrial automation & robotics", "name_zh": "工业自动化与机器人", "icon": "🦾"},
    {"id": "sec_medical_devices", "name_en": "Medical devices & diagnostics", "name_zh": "医疗器械与诊断", "icon": "🩺"},
    {"id": "sec_biotech_pharma_rd", "name_en": "Biotech & pharma R&D", "name_zh": "生物技术与药物研发", "icon": "🧬"},
    {"id": "sec_health_insurance", "name_en": "Health insurance & payers", "name_zh": "健康保险与支付方", "icon": "📋"},
    {"id": "sec_logistics_freight_tech", "name_en": "Logistics & freight technology", "name_zh": "物流与货运科技", "icon": "📲"},
    {"id": "sec_construction_tech", "name_en": "Construction technology", "name_zh": "建筑科技", "icon": "🏗️"},
    {"id": "sec_prop_tech", "name_en": "Prop-tech & real estate platforms", "name_zh": "地产科技与房产平台", "icon": "🏠"},
    {"id": "sec_ed_tech", "name_en": "Education technology", "name_zh": "教育科技", "icon": "📱"},
    {"id": "sec_media_streaming", "name_en": "Streaming & digital media", "name_zh": "流媒体与数字媒体", "icon": "🎬"},
    {"id": "sec_gaming", "name_en": "Gaming & interactive entertainment", "name_zh": "游戏与互动娱乐", "icon": "🎮"},
    {"id": "sec_hospitality_tech", "name_en": "Hospitality technology", "name_zh": "酒店与餐饮科技", "icon": "🏨"},
    {"id": "sec_consumer_goods", "name_en": "Consumer packaged goods (CPG)", "name_zh": "快消品（CPG）", "icon": "🧴"},
    {"id": "sec_luxury_retail", "name_en": "Luxury goods & premium retail", "name_zh": "奢侈品与高端零售", "icon": "💎"},
    {"id": "sec_agriculture_commodities", "name_en": "Agricultural commodities trading", "name_zh": "农产品大宗商品贸易", "icon": "📉"},
    {"id": "sec_chemicals_specialty", "name_en": "Specialty chemicals", "name_zh": "特种化学品", "icon": "⚗️"},
    {"id": "sec_waste_recycling", "name_en": "Recycling & circular economy", "name_zh": "回收与循环经济", "icon": "♻️"},
    {"id": "sec_space_tech", "name_en": "Space technology & satellite services", "name_zh": "航天科技与卫星服务", "icon": "🛰️"},
    {"id": "sec_quantum", "name_en": "Quantum computing & research services", "name_zh": "量子计算与研究服务", "icon": "🌀"},
    {"id": "sec_climate_carbon", "name_en": "Climate tech & carbon markets", "name_zh": "气候科技与碳市场", "icon": "🌍"},
    {"id": "sec_legal_tech", "name_en": "Legal technology", "name_zh": "法律科技", "icon": "⚖️"},
    {"id": "sec_hr_tech", "name_en": "HR technology (HCM / ATS)", "name_zh": "人力资源科技", "icon": "👥"},
    {"id": "sec_insurtech", "name_en": "InsurTech", "name_zh": "保险科技", "icon": "📲"},
    {"id": "sec_wealth_tech", "name_en": "WealthTech & robo-advisory", "name_zh": "财富科技与智能投顾", "icon": "💹"},
    {"id": "sec_marketplace_platforms", "name_en": "Multi-sided marketplaces", "name_zh": "多边市场平台", "icon": "🛍️"},
    {"id": "sec_b2b_saas", "name_en": "B2B SaaS (horizontal)", "name_zh": "B2B SaaS（通用型）", "icon": "☁️"},
    {"id": "sec_vertical_saas", "name_en": "Vertical SaaS", "name_zh": "垂直行业 SaaS", "icon": "📊"},
    {"id": "sec_hardware_iot", "name_en": "Hardware, IoT & connected devices", "name_zh": "硬件、物联网与联网设备", "icon": "📡"},
    {"id": "sec_energy_utilities_tech", "name_en": "Energy & utilities technology", "name_zh": "能源与公用事业科技", "icon": "💡"},
]
